controller_manager:
  ros__parameters:
    update_rate: 1000 #Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    forward_position_controller:
      type: forward_command_controller/forward_command_controller

forward_position_controller:
  ros_parameters:
    joints:
      - wrist_link
    interface_name: position